# Generated by Django 3.1 on 2020-09-04 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
